# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pair_work.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 960)
        MainWindow.setStyleSheet("background-color:rgb(239, 213, 246)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.View = QtWidgets.QGraphicsView(self.centralwidget)
        self.View.setGeometry(QtCore.QRect(60, 10, 1081, 781))
        self.View.setObjectName("View")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 830, 751, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choose = QtWidgets.QPushButton(self.layoutWidget)
        self.choose.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.choose.setObjectName("choose")
        self.horizontalLayout.addWidget(self.choose)
        self.Read = QtWidgets.QPushButton(self.layoutWidget)
        self.Read.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.Read.setObjectName("Read")
        self.horizontalLayout.addWidget(self.Read)
        self.mess = QtWidgets.QPushButton(self.layoutWidget)
        self.mess.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.mess.setObjectName("mess")
        self.horizontalLayout.addWidget(self.mess)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(230, 900, 751, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Save = QtWidgets.QPushButton(self.layoutWidget1)
        self.Save.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.Save.setObjectName("Save")
        self.horizontalLayout_2.addWidget(self.Save)
        self.Close = QtWidgets.QPushButton(self.layoutWidget1)
        self.Close.setStyleSheet("background-color:rgb(170, 170, 255)")
        self.Close.setObjectName("Close")
        self.horizontalLayout_2.addWidget(self.Close)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Close.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose.setText(_translate("MainWindow", "choose a pic"))
        self.Read.setText(_translate("MainWindow", "read progress"))
        self.mess.setText(_translate("MainWindow", "mess up"))
        self.Save.setText(_translate("MainWindow", "save progress"))
        self.Close.setText(_translate("MainWindow", "close"))
